[platformio]
; Tell PIO to treat this folder (containing .ino) as the source directory
src_dir = .


[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/thomasfredericks/MicroRemoteWire
   thomasfredericks/M5_PbHub@^0.1.4
    FastLED
    https://github.com/thomasfredericks/MicroOsc.git
    pololu/VL53L0X
    https://github.com/thomasfredericks/M5_Encoder.git